In [117]:
import pandas as pd
from pathlib import Path

In [118]:
#Entrando no caminho dos arquivos
DATA_PATH = Path("../data/raw")

files = list(DATA_PATH.glob("*.csv"))

for file in files:
    print(file.name)

olist_customers_dataset.csv
olist_geolocation_dataset.csv
olist_orders_dataset.csv
olist_order_items_dataset.csv
olist_order_payments_dataset.csv
olist_order_reviews_dataset.csv
olist_products_dataset.csv
olist_sellers_dataset.csv
product_category_name_translation.csv

In [119]:
# Carregando os datasets em um dicionário
datasets = {}

for file in files:
    name = file.stem
    datasets[name] = pd.read_csv(file)

print(f"{len(datasets)} datasets carregados.")

9 datasets carregados.

In [120]:
# Printando a forma de cada dataset
for name, df in datasets.items():
    print(f"{name}: {df.shape}")

olist_customers_dataset: (99441, 5)
olist_geolocation_dataset: (1000163, 5)
olist_orders_dataset: (99441, 8)
olist_order_items_dataset: (112650, 7)
olist_order_payments_dataset: (103886, 5)
olist_order_reviews_dataset: (99224, 7)
olist_products_dataset: (32951, 9)
olist_sellers_dataset: (3095, 4)
product_category_name_translation: (71, 2)

In [121]:
# Carregando dataframe
order_items_df = pd.DataFrame(datasets["olist_order_items_dataset"])
products_df_clean = pd.read_csv("../data/processed/olist_products_dataset_clean.csv")
order_df = pd.DataFrame(datasets["olist_orders_dataset"])
sellers_df = pd.DataFrame(datasets["olist_sellers_dataset"])
order_items_df.shape

(112650, 7)

In [122]:
order_items_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

In [123]:
#Avaliando se existe valores nulos
order_items_df.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [124]:
#Avaliando se existe dados duplicados
order_items_df.duplicated().sum()

np.int64(0)

In [125]:
order_items_df['price'].describe()

count    112650.000000
mean        120.653739
std         183.633928
min           0.850000
25%          39.900000
50%          74.990000
75%         134.900000
max        6735.000000
Name: price, dtype: float64

In [126]:
order_items_df['freight_value'].describe()

count    112650.000000
mean         19.990320
std          15.806405
min           0.000000
25%          13.080000
50%          16.260000
75%          21.150000
max         409.680000
Name: freight_value, dtype: float64

In [127]:
order_items_df.duplicated(subset=['order_id', 'order_item_id']).sum()

np.int64(0)

In [128]:
(order_items_df['freight_value'] == 0).sum()

np.int64(383)

In [129]:
order_items_df.nlargest(10, 'price')

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
3556,0812eb902a67711a1cb742b3cdaa65ae,1,489ae2aa008f021502940f251d4cce7f,e3b4998c7a498169dc7bce44e6bb6277,2017-02-16 20:37:36,6735.00,194.31
112233,fefacc66af859508bf1a7934eab1e97f,1,69c590f7ffc7bf8db97190b6cb6ed62e,80ceebb4ee9b31afb6c6a916a574a1e2,2018-08-02 04:05:13,6729.00,193.21
107841,f5136e38d1a14a4dbd87dff67da82701,1,1bdf5e6731585cf01aa8169c7028d6ad,ee27a8f15b1dded4d213a468ba4eb391,2017-06-15 02:45:17,6499.00,227.66
74336,a96610ab360d42a2e5335a3998b4718a,1,a6492cc69376c469ab6f61d8f44de961,59417c56835dd8e2e72f91f809cd4092,2017-04-18 13:25:18,4799.00,151.34
11249,199af31afc78c699f0dbf71fb178d4d4,1,c3ed642d592594bb648ff4a04cee2747,59417c56835dd8e2e72f91f809cd4092,2017-05-09 15:50:15,4690.00,74.34
62086,8dbc85d1447242f3b127dda390d56e19,1,259037a6a41845e455183f89c5035f18,c72de06d72748d1a0dfb2125be43ba63,2018-06-28 12:36:36,4590.00,91.78
29193,426a9742b533fc6fed17d1fd6d143d7e,1,a1beef8f3992dbd4cd8726796aa69c53,512d298ac2a96d1931b6bd30aa21f61d,2018-08-16 14:24:28,4399.87,113.45
45843,68101694e5c5dc7330c91e1bbc36214f,1,6cdf8fc1d741c76586d8b6b15e9eef30,ed4acab38528488b65a9a9c603ff024a,2018-04-05 08:27:27,4099.99,75.27
78310,b239ca7cd485940b31882363b52e6674,1,dd113cb02b2af9c8e5787e8f1f0722f6,821fb029fc6e495ca4f08a35d51e53a5,2018-08-02 08:15:14,4059.00,104.51
59137,86c4eab1571921a6a6e248ed312f5a5a,1,6902c1962dd19d540807d0ab8fade5c6,fa1c13f2614d7b5c4749cbc52fecda94,2017-03-23 20:08:04,3999.90,17.01

In [130]:
# 10 itens com maior preço
order_items_ids_largest = order_items_df.nlargest(10, 'price')

# Pegar apenas os product_id
product_ids = order_items_ids_largest['product_id']

# Buscar esses produtos no dataframe de produtos
products_df_clean.loc[
    products_df_clean['product_id'].isin(product_ids)
]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
5899,489ae2aa008f021502940f251d4cce7f,utilidades_domesticas,31.0,875.0,2.0,30000.0,60.0,61.0,33.0
9530,c3ed642d592594bb648ff4a04cee2747,eletroportateis,59.0,2217.0,2.0,30000.0,50.0,49.0,50.0
11850,6902c1962dd19d540807d0ab8fade5c6,relogios_presentes,53.0,1773.0,2.0,800.0,16.0,11.0,11.0
13561,dd113cb02b2af9c8e5787e8f1f0722f6,esporte_lazer,51.0,1511.0,1.0,8000.0,55.0,25.0,45.0
14423,1bdf5e6731585cf01aa8169c7028d6ad,artes,28.0,3954.0,2.0,7400.0,47.0,25.0,25.0
21197,a6492cc69376c469ab6f61d8f44de961,eletroportateis,41.0,1780.0,2.0,22600.0,55.0,40.0,40.0
21768,69c590f7ffc7bf8db97190b6cb6ed62e,pcs,50.0,1935.0,4.0,5660.0,54.0,18.0,47.0
24994,259037a6a41845e455183f89c5035f18,pcs,55.0,1710.0,2.0,2900.0,35.0,10.0,40.0
30704,6cdf8fc1d741c76586d8b6b15e9eef30,consoles_games,59.0,3172.0,1.0,3050.0,34.0,10.0,22.0
31224,a1beef8f3992dbd4cd8726796aa69c53,instrumentos_musicais,59.0,944.0,3.0,3550.0,71.0,34.0,22.0

In [131]:
(~order_items_df['product_id'].isin(products_df_clean['product_id'])).sum()

np.int64(0)

In [132]:
(~order_items_df['order_id'].isin(order_df['order_id'])).sum()

np.int64(0)

In [133]:
(~order_items_df['seller_id'].isin(sellers_df['seller_id'])).sum()

np.int64(0)

In [134]:
order_items_df['order_id'].nunique()

98666

In [135]:
order_items_df['order_item_id'].nunique()

21

In [136]:
order_items_df['product_id'].nunique()

32951

In [137]:
order_items_df['seller_id'].nunique()

3095

In [138]:
order_items_df['shipping_limit_date'].isna().sum()

np.int64(0)

In [139]:
order_items_df['shipping_limit_date'].max()

'2020-04-09 22:35:08'

In [140]:
order_items_df['shipping_limit_date'].min()

'2016-09-19 00:15:34'

In [141]:
order_items_df['shipping_limit_date'].head()

0    2017-09-19 09:45:35
1    2017-05-03 11:05:13
2    2018-01-18 14:48:30
3    2018-08-15 10:10:18
4    2017-02-13 13:57:51
Name: shipping_limit_date, dtype: str

In [142]:
order_items_df['shipping_limit_date'] = pd.to_datetime(order_items_df['shipping_limit_date'])
order_items_df['shipping_limit_date'].min()

Timestamp('2016-09-19 00:15:34')

In [143]:
order_items_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  datetime64[us]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 6.0 MB

In [144]:
order_items_clean = order_items_df.copy()

In [145]:
order_items_clean.to_csv('../data/processed/olist_order_items_dataset_clean.csv', index=False)

## 📌 Conclusão da etapa — Order Items

### 🔎 O que foi encontrado?

A tabela `order_items` possui **112.650 registros e 7 colunas**.

Durante o profiling, foram identificados:

- Nenhum valor nulo;
- Nenhuma duplicidade na combinação `order_id + order_item_id`;
- Nenhuma inconsistência nos relacionamentos com `products`, `orders` e `sellers`;
- Nenhum valor negativo nas colunas `price` e `freight_value`;
- A coluna `shipping_limit_date` estava armazenada como `string`, apesar de representar uma informação de data e hora.

### 🛠️ O que foi feito?

Como os dados apresentaram boa qualidade, não foi necessário remover registros ou realizar preenchimento de valores ausentes.

A única alteração realizada foi a conversão da coluna `shipping_limit_date` de `string` para `datetime`, adequando o tipo de dado ao seu significado.

### ✅ Como foi validado?

Após o tratamento, foram realizadas novas verificações para garantir a integridade dos dados:

- A quantidade de registros permaneceu em **112.650**;
- Não foram identificados valores nulos;
- Não foram encontradas duplicidades em `order_id + order_item_id`;
- Os relacionamentos com `products`, `orders` e `sellers` permaneceram íntegros;
- Não foram encontrados valores negativos em `price` e `freight_value`;
- `shipping_limit_date` foi validada como `datetime`.

### 📁 Resultado

O dataset tratado foi salvo em:

`data/processed/olist_order_items_dataset.csv`